export const GET_LIST_SEARCH_AFFILATE_REQUEST =
  'GET_LIST_SEARCH_AFFILATE_REQUEST';
export const GET_LIST_SEARCH_AFFILATE_SUCCESS =
  'GET_LIST_SEARCH_AFFILATE_SUCCESS';
//
export const LOAD_DATA_SEARCH_AFFILATE_REQUEST =
  'LOAD_DATA_SEARCH_AFFILATE_REQUEST';
export const LOAD_DATA_SEARCH_AFFILATE_SUCCESS =
  'LOAD_DATA_SEARCH_AFFILATE_SUCCESS';
export const CHANGE_STATUS_AFFILATES_REQUEST =
  'CHANGE_STATUS_AFFILATES_REUQEST';
export const CHANGE_STATUS_AFFILATES_SUCCESS =
  'CHANGE_STATUS_AFFILATES_SUCCESS';
