export const CREATE_COUPON_ADMIN_REQUEST = 'CREATE_COUPON_ADMIN_REQUEST';
export const CREATE_COUPON_ADMIN_SUCCESS = 'CREATE_COUPON_ADMIN_SUCCESS';
export const CREATE_COUPON_ADMIN_ERROR = 'CREATE_COUPON_ADMIN_ERROR';
///coupon list
export const LOAD_DATA_COUPON_LIST_REQUEST = 'LOAD_DATA_COUPON_LIST_REQUEST';
export const LOAD_DATA_COUPON_LIST_SUCCESS = 'LOAD_DATA_COUPON_LIST_SUCCESS';
export const LOAD_DATA_COUPON_LIST_ERROR = 'LOAD_DATA_COUPON_LIST_ERROR';
///coupon search
export const LOAD_DATA_COUPON_SEARCH_REQUEST =
  'LOAD_DATA_COUPON_SEARCH_REQUEST';
export const LOAD_DATA_COUPON_SEARCH_SUCCESS =
  'LOAD_DATA_COUPON_SEARCH_SUCCESS';
