export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';
export const GET_LIST_CUSTOMER_SUCCESS = 'GET_LIST_CUSTOMER_SUCCESS';

export const GET_LICENSE_LIST_BY_USER = 'GET_LICENSE_LIST_BY_USER';
export const GET_LICENSE_LIST_BY_USER_SUCCESS =
  'GET_LICENSE_LIST_BY_USER_SUCCESS';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
