export const LOAD_SEARCH_HISTORY_REQUEST = 'LOAD_SEARCH_HISTORY_REQUEST';
export const LOAD_SEARCH_HISTORY_SUCCESS = 'LOAD_SEARCH_HISTORY_SUCCESS';
export const LOAD_DATA_HISTORY_REQUEST = 'LOAD_DATA_HISTORY_REQUEST';
export const LOAD_DATA_HISTORY_SUCCESS = 'LOAD_DATA_HISTORY_SUCCESS';
