export const GET_AFFILIATE_PROGRAM = 'GET_AFFILIATE_PROGRAM';
export const GET_AFFILIATE_PROGRAM_SUCCESS = 'GET_AFFILIATE_PROGRAM_SUCCESS';

export const REQUEST_WITHDRAW = 'REQUEST_WITHDRAW';
export const GET_INVOICES_RECEIVE_COMMISSION =
  'GET_INVOICES_RECEIVE_COMMISSION';
export const GET_INVOICES_RECEIVE_COMMISSION_SUCCESS =
  'GET_INVOICES_RECEIVE_COMMISSION_SUCCESS';
export const GET_PRESENTEE = 'GET_PRESENTEE ';
export const GET_PRESENTEE_SUCCESS = 'GET_PRESENTEE_SUCCESS ';
//History
export const LOAD_DATA_HISTORY = 'LOAD_DATA_HISTORY';
export const LOAD_DATA_HISTORY_SUCCESS = 'LOAD_DATA_HISTORY_SUCCESS';
export const LOAD_DATA_HISTORY_ERROR = 'LOAD_DATA_HISTORY_ERROR';
