export const LOGIN_EMAIL = 'LOGIN_EMAIL';
export const LOGIN_AUTHORIZE = 'LOGIN_AUTHORIZE';
export const LOGIN_AUTHORIZE_SUCCESS = 'LOGIN_AUTHORIZE_SUCCESS';
export const EXPIRED_AUTH = 'EXPIRED_AUTH';
export const RESET_EXPIRED_AUTH = 'RESET_EXPIRED_AUTH';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED';
export const RESET_REFRESH = 'RESET_REFRESH';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const RESET_UPDATE_PROFILE_SUCCESS = 'RESET_UPDATE_PROFILE_SUCCESS';

export const GET_PROFILE_USER = 'GET_PROFILE_USER';
export const GET_PROFILE_USER_SUCCESS = 'GET_PROFILE_USER_SUCCESS';
