export const CHECK_COUPON_PROMOTION = 'CHECK_COUPON_PROMOTION';
export const CHECK_COUPON_PROMOTION_RESULT = 'CHECK_COUPON_PROMOTION_RESULT';

export const RESET_COUPON = 'RESET_COUPON';
export const SET_LOADING_CHECK = 'SET_LOADING_CHECK';
