export const GET_PACKAGE_PAGE = 'GET_PACKAGE_PAGE';
export const GET_PACKAGE_PAGE_SUCCESS = 'GET_PACKAGE_PAGE_SUCCESS';

export const PAYMENT = 'PAYMENT';
export const PAYMENT_RESPON = 'PAYMENT_RESPON';
export const PAYMENT_AGAIN = 'PAYMENT_AGAIN';

export const LOADING_PAYMENT = 'LOADING_PAYMENT';
///
export const GET_PACKAGE_ALL_REQUEST = 'GET_PACKAGE_ALL_REQUEST';
export const GET_PACKAGE_ALL_SUCCESS = 'GET_PACKAGE_ALL_SUCCESS';

export const GET_MY_INVOICE_BY_SERVICE = 'GET_MY_INVOICE_BY_SERVICE';
export const GET_MY_INVOICE_BY_SERVICE_SUCCESS =
  'GET_MY_INVOICE_BY_SERVICE_SUCCESS';

export const CANCEL_PAYMENT_REQUEST = 'CANCEL_PAYMENT_REQUEST';
