export const GET_LICENSE_DETAIL_RESULT = 'GET_LICENSE_DETAIL_RESULT';
export const GET_INVOICE_DETAIL_RESULT = 'GET_INVOICE_DETAIL_RESULT';
export const GET_INVOICE_DETAIL_RESULT_SUCCESS =
  'GET_INVOICE_DETAIL_RESULT_SUCCESS';
export const GET_INVOICE_DETAIL_ERROR = 'GET_INVOICE_DETAIL_ERROR';

export const GET_LICENSES_DETAIL_RESULT_SUCCESS =
  'GET_LICENSES_DETAIL_RESULT_SUCCESS';
export const GET_LICENSE_DETAIL_RESULT_ERROR =
  'GET_LICENSE_DETAIL_RESULT_ERROR';
