export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_DETAIL = 'LOAD_DATA_DETAIL';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_UI_SUCCESS = 'LOAD_DATA_UI_SUCCESS';
export const LOAD_DATA_DETAIL_SUCCESS = 'LOAD_DATA_DETAIL_SUCCESS';
export const LOAD_DATA_DETAIL_ERROR = 'LOAD_DATA_DETAIL_ERROR';

export const LOAD_DATA_ERROR = 'LOAD_DATA_ERROR';
///Coupon
export const APPLY_COUPON = 'APPLY_COUPON';
export const CHECK_COUPON_SUCCESS = 'CHECK_COUPON_SUCCESS';
export const CHECK_COUPON_ERROR = 'CHECK_COUPON_ERROR';
